services:
  - type: web
    name: naija-connect
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: PORT
        value: 10000
